AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template to create an EC2 instance in the default subnet and an S3 bucket

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0cce845c391f5743c # Replace with a valid AMI ID
      InstanceType: t2.micro
      SecurityGroups:
        - !Ref InstanceSecurityGroup

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0 # Open SSH to the world (not recommended for production)

  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "my-unique-bucket-${AWS::AccountId}" # Ensure uniqueness

Outputs:
  EC2InstanceId:
    Description: Instance ID of the created EC2 instance
    Value: !Ref MyEC2Instance
  S3BucketName:
    Description: Name of the created S3 bucket
    Value: !Ref MyS3Bucket
